# 无需执行这个声明文件，本文件仅仅为了说明operator会自动生成的资源定义，仅做效果图
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vastbase-pv1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/vastbase/vbdata-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vastbase-pv2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/vastbase/vbdata-2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vastbase-conf-pv1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/vastbase/hasconf-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vastbase-conf-pv2
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/vastbase/hasconf-2"

