# 无需执行这个声明文件，本文件仅仅为了说明operator会自动生成的资源定义，仅做效果图
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: vastbase-pv-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/home/vastbase/vbdata"
