---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vastbase-0
spec:
  resources:
    requests:
      storage: {CAPACITY_DATA}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vastbase-1
spec:
  resources:
    requests:
      storage: {CAPACITY_DATA}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vastbase-2
spec:
  resources:
    requests:
      storage: {CAPACITY_DATA}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-vastbase-0
spec:
  resources:
    requests:
      storage: {CAPACITY_CONF}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-vastbase-1
spec:
  resources:
    requests:
      storage: {CAPACITY_CONF}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-vastbase-2
spec:
  resources:
    requests:
      storage: {CAPACITY_CONF}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual

