FROM centos:7

MAINTAINER yangjie <yangjie>

ENV USER="vastbase" \
    PASSWORD=1qaz@WSX \
    GROUP=vastbase \
    LC_ALL=en_US.utf8
	
RUN useradd ${USER} \
       && yum -y update && yum install -y iptables sudo net-tools iproute  openssh-server openssh-clients which vim sudo crontabs libaio-0.3.109-13.el7.x86_64 zlib libuuid readline systemd-libs openssl krb5-libs libicu libxslt libxml2 tcl perl openldap pam openssl-devel cracklib gettext

#安装database
COPY --chown=${USER}:${USER} vbbase/ /home/${USER}/vbbase
COPY --chown=${USER}:${USER} vbdata/ /home/${USER}/vbdata
COPY --chown=${USER}:${USER} scripts/ /home/${USER}/scripts
COPY --chown=${USER}:${USER} etcd/ /home/${USER}/etcd
COPY --chown=${USER}:${USER} .bashrc /home/${USER}/.bashrc
COPY --chown=${USER}:${USER} logs/ /home/${USER}/log
#切换用户
USER ${USER}
#切换工作目录
WORKDIR /home/${USER}
#启动入口程序
CMD ["/bin/bash", "/home/vastbase/scripts/entrypoint.sh"]
