FROM centos:7

MAINTAINER yangjie <yangjie>

ENV USER="vastbase" \
    PASSWORD=1qaz@WSX \
    GROUP=vastbase \
    LC_ALL=en_US.utf8\
    LANG=en_US.UTF-8 \
    TZ=Asia/Shanghai \
    GAUSSHOME=/home/vastbase/vbbase \
    PGUSER=vastbase \
    PGPORT=5432 \
    PGDATA=/home/vastbase/vbdata \
    LD_LIBRARY_PATH=/home/vastbase/vbbase/lib:/home/vastbase/vbbase/jre/lib/amd64:$LD_LIBRARY_PATH \
    GAUSSHOME=/home/vastbase/vbbase \
    PATH=/home/vastbase/vbbase/bin:$PATH
	
RUN useradd ${USER} \
       && yum -y update && yum install -y iptables sudo net-tools iproute  openssh-server openssh-clients which vim sudo crontabs libaio-0.3.109-13.el7.x86_64 zlib libuuid readline systemd-libs openssl krb5-libs libicu libxslt libxml2 tcl perl openldap pam openssl-devel cracklib gettext && \
    echo "export PGUSER=vastbase" >> /home/vastbase/.bashrc && \
    echo "export PGPORT=5432" >> /home/vastbase/.bashrc && \
    echo "export PGDATA=/home/vastbase/vbdata" >> /home/vastbase/.bashrc && \
    echo "export LD_LIBRARY_PATH=/home/vastbase/vbbase/lib:/home/vastbase/vbbase/jre/lib/amd64:$LD_LIBRARY_PATH" >> /home/vastbase/.bashrc && \
    echo "export GAUSSHOME=/home/vastbase/vbbase" >> /home/vastbase/.bashrc && \
    echo "export PATH=/home/vastbase/vbbase/bin:$PATH" >> /home/vastbase/.bashrc    

#安装database
COPY --chown=${USER}:${USER} vbbase/ /home/${USER}/vbbase
COPY --chown=${USER}:${USER} vbdata/ /home/${USER}/vbdata
COPY --chown=${USER}:${USER} scripts/ /home/${USER}/scripts
COPY --chown=${USER}:${USER} etcd/ /home/${USER}/etcd
COPY --chown=${USER}:${USER} logs/ /home/${USER}/logs
#切换用户
USER ${USER}
#切换工作目录
WORKDIR /home/${USER}
#启动入口程序
CMD ["/bin/bash", "/home/vastbase/scripts/entrypoint.sh"]
