scope: {scope_name}
name: "{curr_node_name}"

restapi:
  listen: {curr_node_ip}:{restapi_port}
  connect_address: {curr_node_ip}:{restapi_port}

etcd:
  hosts: {etcd_hosts}

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
         max_connections: {db_max_connections}
         shared_buffers: {db_shared_buffers}
         work_mem: {db_work_mem}
         log_destination: 'stderr'
         logging_collector: 'on'
         log_directory: '{db_log_dir}'
         log_filename: 'postgresql-%Y-%m-%d.log'
         log_file_mode: 0600
         log_rotation_size: '20MB'
         log_min_duration_statement: 1800000
         log_connections: 'off'
         log_disconnections: 'off'
         log_duration: 'on'
         log_hostname: 'on'
         log_line_prefix: '%m %c %d %p %a %x %n %e '
         log_timezone: 'PRC'
         replication_type: 1
         recovery_max_workers: 4
         password_encryption_type: 0
         wal_level: 'hot_standby'
         hot_standby: 'on'
         most_available_sync: 'on'
         vastbase_login_info: 'false'
         pgxc_node_name: 'vdb'
         remote_read_mode: 'non_authentication'
         archive_mode: 'on'
         license_path: '{db_lic_path}'

  initdb:
  - encoding: UTF8

  pg_hba:
  - host all all 0.0.0.0/0 md5

  users:
    master:
      password: "aA@12345"
      options:
        - createrole
        - createdb
    repl:
      password: "aA@12345"
      options:
        - replication

postgresql:
  callbacks:
    on_start: {patroni_callback_sh}
    on_stop: {patroni_callback_sh}
    on_role_change: {patroni_callback_sh}
  listen: 0.0.0.0:{db_port}
  connect_address: {curr_node_ip}:{db_port}
  use_unix_socket: true
  data_dir: {db_data_dir}
  config_dir: {db_data_dir}
  bin_dir: {db_home}/bin
  vastbase_lib_dir: {db_home}/lib
  vastbase_home: {db_home}
  authentication:
    replication:
      username: vbadmin
      password: "Vbase@admin"
    superuser:
      username: vbadmin
      password: "Vbase@admin"
  parameters:
    unix_socket_directory: '/tmp'
    archive_command: 'cp %p {db_data_dir}/arch/%f'
