apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vastbaseclusterreconciler-cluster-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete","patch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", 'create', "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups:
      - vastbase.vastdata.com
    resources:
      - vastbaseclusters
      - vastbaseclusters/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
