---
apiVersion: vastbase.vastdata.com/v1alpha1
kind: VastbaseCluster
metadata:
  name: vb-cluster
spec:
  replicas: 2
  serviceAccountName: java-vastbase-operator
  secretName: vb-secret
  image: saopack/vastbase-cluster-leak:2.2.5
  containerName: vastbase
  containerPort: 5432
  volumeMounts:
    - name: data
      mountPath: /home/vastbase/vbdata
  pvcStorageSize: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/vastbase/vbdata
  headlessServiceName: vastbase
  vastbasePersistentStorageMountName: data
  vastbasePersistentStorageMountPath: /home/vastbase/vbdata
  statefulSetName: vastbase
  vastbaseReadServiceName: vastbase-read
  vastbaseWriteServiceName: vastbase-readwrite
  vastbaseServiceReadNodePort: 30088
  vastbaseServiceWriteNodePort: 30090
  namespace: default

