---
apiVersion: v1
kind: Service
metadata:
  name: vastbase #pod dns通信
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: vsql
    - port: 5433
      protocol: TCP
      targetPort: 5433
      name: localport
    - port: 2380
      protocol: TCP
      targetPort: 2380
      name: etcd1-service
    - port: 2379
      protocol: TCP
      targetPort: 2379
      name: etcd1-local
  selector:
    app: vastbase
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: vastbase-read #所有节点提供读功能
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: vsql
      nodePort: 30088
  selector:
    app: vastbase
---
apiVersion: v1
kind: Service
metadata:
  name: vastbase-readwrite #主节点提供读写功能
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: vsql
      nodePort: 30090
  selector:
    app: vastbase
    role: master
