---
apiVersion: vastbase.vastdata.com/v1alpha1
kind: VastbaseCluster
metadata:
  name: my-replica
spec:
  replicas: 1
  image: saopack/vastbase:2.2.5mod
  containerName: vastbase
  resourceLimits:
    memory: "256Mi"
    cpu: "500m"
  containerPort: 5432
  volumeMounts:
    - name: vastbase-persistent-storage
      mountPath: /data/vastdata
    - name: vastbasecnf
      mountPath: /data/vastdata/postgresql.conf
      subPath: data/vastdata/postgresql.conf
  pvcStorageSize: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/vastdata
  pvName: vastbase-pv-volume
  pvcName: vastbase-pv-claim
  configMapName: mycnf
  headlessServiceName: vastbase
  vastbasePersistentStorageMountName: vastbase-persistent-storage
  vastbaseCnfMountName: vastbasecnf
  vastbasePersistentStorageMountPath: /data/vastdata
  vastbaseCnfMountPath: /data/vastdata/postgresql.conf
  vastbaseCnfMountSubPath: data/vastdata/postgresql.conf
  volumeConfigName: vastbasecnf
  statefulSetName: vastbase
  vastbaseServiceName: vastbase-read
  vastbaseServiceNodePort: 30033

