---
apiVersion: v1
kind: Service
metadata:
  name: vastbase-operator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: vastbase-operator
